# Generated by Django 5.2.1 on 2025-05-23 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id_ride", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("pickup_latitude", models.FloatField(null=True)),
                ("pickup_longitude", models.FloatField(null=True)),
                ("dropoff_latitude", models.FloatField(null=True)),
                ("dropoff_longitude", models.FloatField(null=True)),
                ("pickup_time", models.DateTimeField(null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        db_column="id_driver",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        db_column="id_rider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride",
                "verbose_name_plural": "Rides",
                "db_table": "ride",
            },
        ),
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                ("id_ride_event", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ride",
                    models.ForeignKey(db_column="id_ride", on_delete=django.db.models.deletion.CASCADE, to="ride.ride"),
                ),
            ],
            options={
                "verbose_name": "Ride Event",
                "verbose_name_plural": "Ride Events",
                "db_table": "ride_event",
            },
        ),
    ]
