# Generated by Django 5.2.1 on 2025-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("id_user", models.BigAutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(blank=True, max_length=20, verbose_name="user role")),
                ("first_name", models.TextField(blank=True, verbose_name="first name")),
                ("last_name", models.TextField(blank=True, verbose_name="last name")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="email address")),
                ("phone_number", models.CharField(blank=True, max_length=50, verbose_name="phone number")),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
    ]
